# Generated by Django 2.1.5 on 2019-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190829_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppCreatModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('appname', models.CharField(max_length=200, unique=True)),
                ('accesskey', models.CharField(default='waiting', max_length=200)),
                ('secretkey', models.CharField(default='waiting', max_length=200)),
            ],
            options={
                'db_table': 'userapps',
            },
        ),
        migrations.AlterField(
            model_name='cloudusersmodel',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cloudusersmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cloudusersmodel',
            name='status',
            field=models.CharField(default='waiting', max_length=100),
        ),
    ]
