# Generated by Django 2.1.5 on 2019-08-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190831_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('appname', models.CharField(max_length=200)),
                ('accesskey', models.CharField(max_length=200)),
                ('secretkey', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('userfile', models.FileField(upload_to='media/')),
            ],
            options={
                'db_table': 'userfiles',
            },
        ),
    ]
